module.exports = [
  {name: 'account', methods: ['create', 'delete', 'update', 'query']},
  {name: 'accountingCode', methods: ['create', 'update', 'query']},
  {name: 'accountingPeriod', methods: ['create', 'update', 'query']},
  {name: 'amendment', methods: ['amend', 'create', 'delete', 'update', 'query']},
  {name: 'billRun', methods: ['create', 'delete', 'update', 'query']},
  {name: 'communicationProfile'},
  {name: 'contact'},
  {name: 'creditBalanceAdjustment'},
  {name: 'export', methods: ['create', 'delete', 'query']},
  {name: 'feature', methods: ['create', 'delete', 'update', 'query']},
  {name: 'import'},
  {name: 'Invoice'},
  {name: 'InvoiceAdjustment'},
  {name: 'InvoiceFile'},
  {name: 'InvoiceItem'},
  {name: 'InvoiceItemAdjustment'},
  {name: 'InvoicePayment'},
  {name: 'InvoiceSplit'},
  {name: 'InvoiceSplitItem'},
  {name: 'Payment'},
  {name: 'PaymentMethod'},
  {name: 'PaymentMethodSnapshot', methods: ['query']},
  {name: 'Product'},
  {name: 'ProductFeature'},
  {name: 'ProductRatePlan'},
  {name: 'ProductRatePlanCharge'},
  {name: 'ProductRatePlanChargeTier'},
  {name: 'RatePlan'},
  {name: 'RatePlanCharge'},
  {name: 'RatePlanChargeTier'},
  {name: 'Refund'},
  {name: 'RefundInvoicePayment'},
  {name: 'Subscription', methods: ['delete', 'update', 'query']},
  {name: 'SubscriptionProductFeature'},
  {name: 'TaxationItem'},
  {name: 'UnitOfMeasure'},
  {name: 'Usage'},
  {name: 'BillingPreviewRequest'}, //BillingPreviewRequest
  {name: 'Request'},               //BillingPreviewRequest
  {name: 'BillingPreviewRun', methods: ['create', 'query']},
  {name: 'GenerateInvoice', methods: ['subscribe']},
  {name: 'ProcessPayments', methods: ['subscribe']}
];
